---
- hosts: app
  become: yes
  tasks:
   - name: install the httpd rpm on server
     yum: name=httpd state=present
   - name: start the httpd service
     service: name=httpd state=started
   - name: open port 80
     firewalld: service=http permanent=true state=enabled
   - name: start the firewalld service
     service: name=firewalld state=restarted
   - name: restart apache
     service: name=httpd state=restarted
